import type { Metadata } from "next";
import { Geist, Geist_Mono, Bungee } from "next/font/google";
import { CartProvider } from "./context/CartContext";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import Background from "./components/Background";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bungee = Bungee({
  variable: "--font-bungee",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Murilo Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${bungee.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <CartProvider>
          <Background />
          <Header />
          <Sidebar />
          <main className="font-mono">
            {children}
          </main>
        </CartProvider>
      </body>
    </html>
  );
}